### ISSUE TITLE
Allow ignoring of elements which match a certain CSS selector

### ISSUE THREAD

**Issue by rowanmanning** [springernature/pa11y#108]
This would allow you to ignore elements on the page that are out of your control, such as advertisements or other third-party code. Open to suggestions on the JS/CLI APIs.

**Comment by hollsk** [comment]
Idea: have Pa11y ignore anything inside an element with aria-hidden or HTML5 hidden applied to it. 

Inspiration here: https://www.paciellogroup.com/blog/2012/05/html5-accessibility-chops-hidden-and-aria-hidden/

Table detailing test results for those attributes in various combinations of browsers and screen readers is here: http://www.html5accessibility.com/tests/hidden2013.html

**Comment by davidjb** [comment]
+1.  In my case I'm interested in also ignoring everything *but* a specific selector, so perhaps include/exclude options would satisfy both.  Having pa11y test the whole page but just filter the report output could be a solution.

In my specific use case, I have documentation pages from an upstream web framework and want to test a specific selector on each page (eg excluding everything else).

**Comment by GlynnPhillips** [comment]
I might try and have a think about this and propose something.

I think its worth mentioning that [this feature](https://github.com/nature/pa11y/pull/130) should make its way into the next release of Pa11y and it would allow you to manipulate the page to get the same result. It would of course require slightly more work on the user end

**Comment by GlynnPhillips** [comment]
After taking a look at this and thinking about @hollsk suggestion it turns out HTML CodeSniffer already ignores items within HTML5 `hidden` attributes. 

The ability to rely on functionality already available within HTML CodeSniffer make this much easier to implement. Within https://github.com/nature/pa11y/blob/master/lib/inject.js we could manipulate the DOM to add the `hidden` attribute to elements that match the selectors.

I imagine the option would be something like `-h, --hide` and would be passed an array of selectors.

Unfortunately HTML CodeSniffer doesn't appear to already support the `aria-hidden` attribute however this is something we could potential pull request into their code base.

@davidjb I think your user case is slightly out of scope of this change as the implementation would be different. I will open a new issue for this instead of trying to combine it with this change.

**Comment by GlynnPhillips** [comment]
This has now been released in `3.6.0` https://github.com/springernature/pa11y#hideelements-string
